### ISSUE TITLE
cURL error 6: Could not resolve host: Version 3.0

### ISSUE THREAD

**Issue by manuelgeek** [SmoDav/mpesa#14]
SmoDav \ Mpesa \ Exceptions \ ErrorException
cURL error 6: Could not resolve host: production.safaricom.co.ke (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
gets this error on the latest project i'm working on, initial ealier implementatins works well, 
on same version 3.0,
any solutions to this?

**Comment by SmoDav** [comment]
Please read the documentation. You are to change the production endpoint to the one provided by safaricom.

**Comment by manuelgeek** [comment]
Solved it by copying the initial folder in vendor/smodav of my initial project to the new, its now working, might be the new updates.
Updates
Thank you
