### ISSUE TITLE
ReferenceID

### ISSUE THREAD

**Issue by muvans** [SmoDav/mpesa#2]
Why do you have to use numeric here even when any string works? Is it a limitation on Safaricom end? After commenting out this check, my call still works!

    public function usingReferenceId($referenceId)
    {
        if (!is_numeric($referenceId)) {
            throw new \InvalidArgumentException('The reference id must be numeric');
        }
        $this->referenceId = $referenceId;
        return $this;
    }

**Comment by SmoDav** [comment]
Hi,
Thanks for the update. The reference ID was set to be numeric by Safaricom but was updated to allow strings. Forgot to update it but now it's all good.

**Comment by muvans** [comment]
Thanks boss...That will help guys doing this...You could update the docs
too..to give a hint...


*Regards,*
*Evans Ndegwa,*
*Founder & CEO,*

*Phone*:    +254-723-220235
               +254-733-949310
*Skype*:    muvatech
*Website*: http://www.muva.co.ke
