### ISSUE TITLE
error in simulation

### ISSUE THREAD

**Issue by kchizi** [SmoDav/mpesa#29]
ErrorException in Simulate.php line 130:
Undefined property: SmoDav\Mpesa\C2B\Simulate::$store

**Comment by SmoDav** [comment]
I assume you’re a developer right?

**Comment by kchizi** [comment]
Yes I am :) Thank you for the fix.

**Comment by SmoDav** [comment]
Next time don’t just make an issue, make a PR also with a suggested fix... contribution :)

**Comment by kchizi** [comment]
I will do that. I take this as an invitation to contribute.
