### ISSUE TITLE
Registration of Callback Routes for Production

### ISSUE THREAD

**Issue by henimmans** [SmoDav/mpesa#36]
Thanks for this package! I am facing problems with registering my callback routes, I keep getting the error shown in the attached image... please help
![Selection_004](https://user-images.githubusercontent.com/8249407/59609610-65897900-9120-11e9-87ac-c32707b44128.png)

**Comment by SmoDav** [comment]
Hey, check that you have the correct access keys from Safaricom.

**Comment by henimmans** [comment]
Still not successful. The keys are okay...

**Comment by henimmans** [comment]
Just to ask, anything that I have to do with the Production URLs that were sent to my email? My sandbox is set to false meaning I should be able to hit the production URLS.

**Comment by SmoDav** [comment]
No, the package changes the URLs when you have set `'sandbox' => false,` in the configuration
