### ISSUE TITLE
Unable to initiate STK PUSH

### ISSUE THREAD

**Issue by kyien** [SmoDav/mpesa#42]
i'm having trouble calling the stk class.i'm getting the following error:

SmoDav\Mpesa\Exceptions\ConfigurationException: Invalid consumer key and secret combination in file /var/www/DaiwasaApp/vendor/smodav/mpesa/src/Mpesa/Auth/Authenticator.php on line 101
Stack trace:
laravel 5.8

**Comment by codingedward** [comment]
This is likely an issue with your configuration as everything works fine on my end.

**Comment by SmoDav** [comment]
Make sure you’ve enabled Lipa Na Mpesa on the developers portal

**Comment by kyien** [comment]
Thanks guys i found out that the my client key and secret had an issue .
