### ISSUE TITLE
Service Provider Not Found

### ISSUE THREAD

**Issue by gakenge** [SmoDav/mpesa#5]
The latest update to the package throws this error upon publishing

Class 'SmoDav\Mpesa\Laravel\ServiceProvider' not found 

Is there a fix to this?

**Comment by SmoDav** [comment]
The latest update is on dev-master thus it is not stable. Use the stable version instead

**Comment by gakenge** [comment]
While installing using composer on Laravel,it fetches version 2.0 which I assume is the latest stable version right? But it still throws that error

**Comment by SmoDav** [comment]
Then follow the instructions on branch 2.0

**Comment by WolfTyler** [comment]
Ok, thanks. Is tgere

**Comment by gakenge** [comment]
Is there a timeline for the stable release of version 3?

**Comment by WolfTyler** [comment]
Is there a timeline for the stable release of version 3?
