### ISSUE TITLE
The operator does not exist

### ISSUE THREAD

**Issue by DennisMuchiri** [SmoDav/mpesa#50]
i'g getting this on my callback url after successfull CustomerBuyGoodsOnline

```
'Body' => 
  array (
    'stkCallback' => 
    array (
      'MerchantRequestID' => '7588-31800016-1',
      'CheckoutRequestID' => 'ws_CO_270920212128259339',
      'ResultCode' => 'SFC_IC0003',
      'ResultDesc' => 'The operator does not exist.',
    ),
  ),
)
```

**Comment by DennisMuchiri** [comment]
hi @SmoDav please assist

**Comment by ojrealdev** [comment]
GeHow did you fix this?

**Comment by Omballa** [comment]
Hi @ojrealdev. I found out that this issue might be caused by the two.
1. Ensure you set "TransactionType": "CustomerBuyGoodsOnline" if you are using a Till Number.
2. Ensure you are passing the till number as "PartyB" and not the Business short code.

Hope this helps.

**Comment by anony45** [comment]
Thank you @Omballa this worked for me.

**Comment by ojrealdev** [comment]
It worked. Thank you.
________________________________

**Comment by lincontroy** [comment]
> Hi @ojrealdev. I found out that this issue might be caused by the two.
> 
> 1. Ensure you set "TransactionType": "CustomerBuyGoodsOnline" if you are using a Till Number.
> 2. Ensure you are passing the till number as "PartyB" and not the Business short code.
> 
> Hope this helps.

this worked for me.

**Comment by Mllexx** [comment]
> Hi @ojrealdev. I found out that this issue might be caused by the two.
> 
> 1. Ensure you set "TransactionType": "CustomerBuyGoodsOnline" if you are using a Till Number.
> 2. Ensure you are passing the till number as "PartyB" and not the Business short code.
> 
> Hope this helps.

Thank you, worked for me. I wonder why they do not provide that clarification in the Docs.

**Comment by Binary-Bros-KE** [comment]
Much Appreciation, this worked instantly

**Comment by Cavein254** [comment]
Thanks. Works as expected. If you are using the sandbox use a working tillnumber e.g. our own till as `PartyB`

**Comment by ndegwamoche** [comment]
You have save my life

CustomerBuyGoodsOnline it is

**Comment by cosmoninja** [comment]
This works, PartyB needs to be the actual Till Number. I was loosing my remaining hair.

**Comment by vomondi154** [comment]
Any one with an idea how I can resolve this. The partyB is set correctly
{"Result":{"ResultType":0,"ResultCode":"SFC_IC0003","ResultDesc":"Receiver party is invalid"
