### ISSUE TITLE
Provision for both v1 and v2

### ISSUE THREAD

**Issue by dedanirungu** [SmoDav/mpesa#58]
You have made an update to only reference v1. what about we make it configurable to cover both v1 and v2?
In case Safaricom reintroduces v2 the SmoDav/mpesa package will still have provision for it.

**Comment by SmoDav** [comment]
The v2 changes will affect the response, so the code will need to change to accommodate that, not just the URL

**Comment by dedanirungu** [comment]
Ok.

You therefore cancel my pull request.
