### ISSUE TITLE
Determining Transaction Response

### ISSUE THREAD

**Issue by gakenge** [SmoDav/mpesa#6]
Hi,

How would I know, programmatically if the transaction was successful or unsuccessful? E.g if the client's account has insufficient balance to complete the transaction or if the money was wired successfully to my account?

**Comment by SmoDav** [comment]
Read the documentation.

callback_url: string
This is a fully qualified http endpoint that will be be queried by Safaricom's API on completion or failure of the transaction. It should point to the notification endpoint for your application where you can finalize the checkout process.

**Comment by gakenge** [comment]
I had read it, what I'm not entirely certain about is exactly how is the
code for the callback url supposed to be? Sorry I should've been more
specific but if you could please elaborate on this, I'd be more than
thankful.

**Comment by SmoDav** [comment]
Read the MPesa online checkout documentation from Safaricom. It has all the details. Also use the verification part of the package. Please don't post anything that is not an issue or a bug
